apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello1
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - env >> /etc/envtemp
          restartPolicy: OnFailure

